# Generated by Django 4.1.5 on 2023-02-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="image URL"),
        ),
    ]
