# Generated by Django 4.2.2 on 2023-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_collation="case_insensitive", max_length=254, unique=True, verbose_name="email"),
        ),
    ]
