# Generated by Django 4.2.2 on 2023-06-25 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP EXTENSION IF EXISTS "citext"',
            reverse_sql='CREATE EXTENSION IF NOT EXISTS "citext"',
        )
    ]
