version: '3.7'

services:

  django:
    container_name: meme-wars-django
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./api/src:/app/src/

  postgres:
    container_name: meme-wars-postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - meme-wars-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meme-wars-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - meme-wars-pgadmin-data:/var/lib/pgadmin

  react:
    container_name: meme-wars-react
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/src

volumes:
  meme-wars-postgres-data:
  meme-wars-pgadmin-data:
