version: '3.7'

services:

  django:
    container_name: memewars-django${CONTAINERS_SUFFIX}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src/
      - ./scripts/:/app/scripts/
      - ./requirements:/app/requirements/

  postgres:
    container_name: memewars-postgres${CONTAINERS_SUFFIX}
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - memewars-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: memewars-pgadmin${CONTAINERS_SUFFIX}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - memewars-pgadmin-data:/var/lib/pgadmin

volumes:
  memewars-postgres-data:
  memewars-pgadmin-data:
