# Generated by Django 3.2.9 on 2022-09-18 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlistment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlistments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Enlistment',
                'verbose_name_plural': 'Enlistments',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to='memes', verbose_name='image')),
                ('enlistment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='meme_wars.enlistment', verbose_name='enlistment')),
            ],
            options={
                'verbose_name': 'Meme',
                'verbose_name_plural': 'Memes',
            },
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('has_ended', models.BooleanField(default=False, help_text='If the war has ended, it will not accept new enlistments or votes. Results of the war will be available on the API only after the war ends.', verbose_name='has ended')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
            ],
            options={
                'verbose_name': 'War',
                'verbose_name_plural': 'Wars',
            },
        ),
        migrations.CreateModel(
            name='VotingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('label', models.CharField(max_length=250, verbose_name='label')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_scores', to='meme_wars.war', verbose_name='war')),
            ],
            options={
                'verbose_name': 'Voting Score',
                'verbose_name_plural': 'Voting Scores',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('submission_count', models.IntegerField(default=1, verbose_name='total submissions')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meme_wars.meme', verbose_name='meme')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meme_wars.votingscore', verbose_name='score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddField(
            model_name='enlistment',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlistments', to='meme_wars.war', verbose_name='war'),
        ),
    ]
