# Generated by Django 3.2.9 on 2022-10-02 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme_wars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingscore',
            name='war',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='enlistment',
        ),
        migrations.RemoveField(
            model_name='war',
            name='has_ended',
        ),
        migrations.RemoveField(
            model_name='war',
            name='is_published',
        ),
        migrations.AddField(
            model_name='meme',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='memes', to='users.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='war',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='memes', to='meme_wars.war', verbose_name='war'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='war',
            name='phase',
            field=models.CharField(choices=[('preparation', 'preparation'), ('submission', 'submission'), ('voting', 'voting'), ('finished', 'finished')], default='preparation', max_length=12, verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='score'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enlistment',
        ),
        migrations.DeleteModel(
            name='VotingScore',
        ),
    ]
